-- MySQL Script generated by MySQL Workbench
-- ter 06 abr 2021 10:24:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_espelho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_espelho` (
  `espelho` VARCHAR(10) NOT NULL,
  `volume_previsto` INT ZEROFILL NULL,
  `peso_previsto` FLOAT ZEROFILL NULL,
  `volume_real` INT ZEROFILL NULL,
  `peso_real` FLOAT ZEROFILL NULL,
  PRIMARY KEY (`espelho`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_produto` (
  `cod` INT ZEROFILL NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `peso` FLOAT ZEROFILL NULL,
  PRIMARY KEY (`cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_carregamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_carregamento` (
  `volume` VARCHAR(30) NOT NULL,
  `tb_espelho_espelho` VARCHAR(10) NOT NULL,
  `tb_produto_cod` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`volume`),
  INDEX `fk_tb_carregamento_tb_espelho1_idx` (`tb_espelho_espelho` ASC) VISIBLE,
  INDEX `fk_tb_carregamento_tb_produto1_idx` (`tb_produto_cod` ASC) VISIBLE,
  CONSTRAINT `fk_tb_carregamento_tb_espelho1`
    FOREIGN KEY (`tb_espelho_espelho`)
    REFERENCES `mydb`.`tb_espelho` (`espelho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_carregamento_tb_produto1`
    FOREIGN KEY (`tb_produto_cod`)
    REFERENCES `mydb`.`tb_produto` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_espelho_detalhado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_espelho_detalhado` (
  `tb_produto_cod` INT ZEROFILL NOT NULL,
  `tb_espelho_espelho` VARCHAR(10) NOT NULL,
  `volume_previsto` INT ZEROFILL NOT NULL,
  `peso_previsto` FLOAT ZEROFILL NOT NULL,
  `volume_real` INT ZEROFILL NOT NULL,
  `peso_real` FLOAT ZEROFILL NOT NULL,
  PRIMARY KEY (`tb_produto_cod`, `tb_espelho_espelho`),
  INDEX `fk_tb_espelho_detalhado_tb_espelho_idx` (`tb_espelho_espelho` ASC) VISIBLE,
  INDEX `fk_tb_espelho_detalhado_tb_produto1_idx` (`tb_produto_cod` ASC) VISIBLE,
  CONSTRAINT `fk_tb_espelho_detalhado_tb_espelho`
    FOREIGN KEY (`tb_espelho_espelho`)
    REFERENCES `mydb`.`tb_espelho` (`espelho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_espelho_detalhado_tb_produto1`
    FOREIGN KEY (`tb_produto_cod`)
    REFERENCES `mydb`.`tb_produto` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
